# Generated by Django 5.2.4 on 2025-07-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_released_movie_director_movie_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date_released',
        ),
        migrations.AddField(
            model_name='movie',
            name='year_released',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
