# Generated by Django 5.2.4 on 2025-07-28 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_date_released_movie_year_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hls_folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='hls_playlist',
            field=models.FileField(blank=True, null=True, upload_to='hls/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='processing_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='processing_status',
            field=models.IntegerField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_bitrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_codec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/original/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mkv'])]),
        ),
    ]
